/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tic.tac.toe;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author Bramerz
 */

public class GUI extends javax.swing.JFrame {

    Model model;
    
    /*
        1 for X and 2 for 0
        Same Convention followed in Model Class
    */
    int playerTurn;
    
    /**
     * Creates new form GUI
     */
    
    public GUI() {
        initComponents();
        model = new Model();
        playerTurn = 1;
        JTurnMessage.setText("Player X Turn");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        
    void getMove(JButton b)
    {   
        JInValidMove.setText("");
        
        int x = -1;
        int y = -1;
        
        if(b == J11)
        {
            x = 0;
            y = 0;
        }
        
        if(b == J12)
        {
            x = 0;
            y = 1;
        }
        
        if(b == J13)
        {
            x = 0;
            y = 2;
        }
        
        if(b == J21)
        {
            x = 1;
            y = 0;
        }
        
        if(b == J22)
        {
            x = 1;
            y = 1;
        }
        
        if(b == J23)
        {
            x = 1;
            y = 2;
        }
        
        if(b == J31)
        {
            x = 2;
            y = 0;
        }
        
        if(b == J32)
        {
            x = 2;
            y = 1;
        }
        
        if(b == J33)
        {
            x = 2;
            y = 2;
        }
        
        if(b.getText().equals(""))
        {
            if(playerTurn == 1)
            {
                JTurnMessage.setText("");
                b.setText("X");
                JTurnMessage.setText("Player O Turn");
            }
            
            if(playerTurn == 2)
            {
                JTurnMessage.setText("");
                b.setText("O");
                JTurnMessage.setText("Player X Turn");
            }
        
            playerTurn = model.getTurn(x, y, playerTurn);
            
            boolean f1 = model.isXWinner();
            boolean f2 = model.isOWinner();
            boolean f3 = model.isDraw();
            
            if(f1)
                isWinner(1);
            
            if(f2)
                isWinner(2);
            
            if(f3)
                isWinner(3);
        
        }
        
        else
        {
            //System.out.println("Invalid Move");
            JInValidMove.setText("Invalid Move");
        }
        
    }
    
    void isWinner(int winner)
    {
        if(winner == 1)
        {
            JDisplayMessage.setText("X Wins");
            model.endGame(this);
        }
        
        if(winner == 2)
        {
            JDisplayMessage.setText("O Wins");
            model.endGame(this);
        }
        
        if(winner == 3)
        {
            JDisplayMessage.setText("Game Draw");
            model.endGame(this);
        }
    }
    
    void reset()
    {
        J11.setText("");
        J12.setText("");
        J13.setText("");
        J21.setText("");
        J22.setText("");
        J23.setText("");
        J31.setText("");
        J32.setText("");
        J33.setText("");
        
        JTurnMessage.setText("Player X Turn");
        //JDisplayMessage.setText("");
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        J11 = new javax.swing.JButton();
        J12 = new javax.swing.JButton();
        J13 = new javax.swing.JButton();
        J21 = new javax.swing.JButton();
        J22 = new javax.swing.JButton();
        J23 = new javax.swing.JButton();
        J31 = new javax.swing.JButton();
        J32 = new javax.swing.JButton();
        J33 = new javax.swing.JButton();
        JDisplayMessage = new javax.swing.JLabel();
        JResetButton = new javax.swing.JButton();
        JInValidMove = new javax.swing.JLabel();
        JTurnMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));
        setForeground(new java.awt.Color(51, 0, 51));
        setPreferredSize(new java.awt.Dimension(850, 467));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 51));
        jLabel1.setText("Tic-Tac-Toe");

        J11.setBackground(new java.awt.Color(153, 153, 153));
        J11.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        J11.setForeground(new java.awt.Color(102, 0, 51));
        J11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J11ActionPerformed(evt);
            }
        });

        J12.setBackground(new java.awt.Color(153, 153, 153));
        J12.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        J12.setForeground(new java.awt.Color(102, 0, 51));
        J12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J12ActionPerformed(evt);
            }
        });

        J13.setBackground(new java.awt.Color(153, 153, 153));
        J13.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        J13.setForeground(new java.awt.Color(102, 0, 51));
        J13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J13ActionPerformed(evt);
            }
        });

        J21.setBackground(new java.awt.Color(153, 153, 153));
        J21.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        J21.setForeground(new java.awt.Color(102, 0, 51));
        J21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J21ActionPerformed(evt);
            }
        });

        J22.setBackground(new java.awt.Color(153, 153, 153));
        J22.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        J22.setForeground(new java.awt.Color(102, 0, 51));
        J22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J22ActionPerformed(evt);
            }
        });

        J23.setBackground(new java.awt.Color(153, 153, 153));
        J23.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        J23.setForeground(new java.awt.Color(102, 0, 51));
        J23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J23ActionPerformed(evt);
            }
        });

        J31.setBackground(new java.awt.Color(153, 153, 153));
        J31.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        J31.setForeground(new java.awt.Color(102, 0, 51));
        J31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J31ActionPerformed(evt);
            }
        });

        J32.setBackground(new java.awt.Color(153, 153, 153));
        J32.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        J32.setForeground(new java.awt.Color(102, 0, 51));
        J32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J32ActionPerformed(evt);
            }
        });

        J33.setBackground(new java.awt.Color(153, 153, 153));
        J33.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        J33.setForeground(new java.awt.Color(102, 0, 51));
        J33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J33ActionPerformed(evt);
            }
        });

        JDisplayMessage.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        JDisplayMessage.setForeground(new java.awt.Color(102, 0, 51));

        JResetButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JResetButton.setForeground(new java.awt.Color(102, 0, 51));
        JResetButton.setText("RESET");
        JResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JResetButtonActionPerformed(evt);
            }
        });

        JInValidMove.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        JInValidMove.setForeground(new java.awt.Color(102, 0, 51));

        JTurnMessage.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        JTurnMessage.setForeground(new java.awt.Color(102, 0, 51));
        JTurnMessage.setText("Player X Turn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(J11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J12, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(J13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(J31, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(J21, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(J22, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(J23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(J32, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(J33, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JDisplayMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(JInValidMove, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTurnMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(JResetButton)))
                .addGap(475, 475, 475))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JTurnMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JDisplayMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(J12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(J11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(J13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(J23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(J22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(J21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(J31, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(J32, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(J33, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JInValidMove, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JResetButton)
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void J11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J11ActionPerformed
        // TODO add your handling code here:
        getMove(J11);
    }//GEN-LAST:event_J11ActionPerformed

    private void J12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J12ActionPerformed
        // TODO add your handling code here:
        getMove(J12);
    }//GEN-LAST:event_J12ActionPerformed

    private void J13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J13ActionPerformed
        // TODO add your handling code here:
        getMove(J13);
    }//GEN-LAST:event_J13ActionPerformed

    private void J21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J21ActionPerformed
        // TODO add your handling code here:
        getMove(J21);
    }//GEN-LAST:event_J21ActionPerformed

    private void J22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J22ActionPerformed
        // TODO add your handling code here:
        getMove(J22);
    }//GEN-LAST:event_J22ActionPerformed

    private void J23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J23ActionPerformed
        // TODO add your handling code here:
        getMove(J23);
    }//GEN-LAST:event_J23ActionPerformed

    private void J31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J31ActionPerformed
        // TODO add your handling code here:
        getMove(J31);
    }//GEN-LAST:event_J31ActionPerformed

    private void J32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J32ActionPerformed
        // TODO add your handling code here:
        getMove(J32);
    }//GEN-LAST:event_J32ActionPerformed

    private void J33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J33ActionPerformed
        // TODO add your handling code here:
        getMove(J33);
    }//GEN-LAST:event_J33ActionPerformed

    private void JResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JResetButtonActionPerformed
        // TODO add your handling code here:
        model.endGame(this);
        JDisplayMessage.setText("");
    }//GEN-LAST:event_JResetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton J11;
    private javax.swing.JButton J12;
    private javax.swing.JButton J13;
    private javax.swing.JButton J21;
    private javax.swing.JButton J22;
    private javax.swing.JButton J23;
    private javax.swing.JButton J31;
    private javax.swing.JButton J32;
    private javax.swing.JButton J33;
    private javax.swing.JLabel JDisplayMessage;
    private javax.swing.JLabel JInValidMove;
    private javax.swing.JButton JResetButton;
    private javax.swing.JLabel JTurnMessage;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}